name: florist_app
description: Florist App

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # http request
  retrofit: ^3.3.1
  dio: ^4.0.6
  json_annotation: ^4.8.0 #model or entity support
  pretty_dio_logger: ^1.2.0-beta-1 #logger for dio http request

  #local storage
  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3 #local storage support
  #temporary local storage support
  shared_preferences: ^2.0.17

  #widget
  cached_network_image: ^3.2.3 #images support
  reactive_forms: ^14.2.0
  loader_overlay: ^2.1.0 #fully load screen
  badges: ^3.0.2 #badges widget
  fl_chart: ^0.60.0 #line chart widget
  material_dialogs: ^1.1.4 #dialog widget
  google_maps_flutter: ^2.2.3 #google maps widget
  table_calendar: ^3.0.9 #calendar
  modal_bottom_sheet: ^3.0.0-pre
  reactive_forms_annotations: #anotation for generate reactive form widget


  #location support
  geolocator: ^9.0.2

  #permission handler
  permission_handler: ^10.2.0

  #assets generator
  flutter_gen: ^5.1.0+1

  #routing management
  flutter_modular: ^5.0.3

  #state management
  flutter_bloc: ^8.1.1

  #localization, formatting and many more support
  intl: ^0.18.0 # dont upgrade this, will not match with reactive form

  #usecase support
  either_dart: ^0.3.0

  #services locator / dependency injection
  get_it: ^7.2.0

  #model class support
  equatable: ^2.0.5

  #logging utils
  logger: ^1.1.0

dependency_overrides:
  intl: ^0.18.0
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  #widget
  widgetbook: ^2.4.1 #widget preview

  # file generator (model etc)
  build_runner: ^2.3.3
  retrofit_generator: ^4.2.0 # retrofit support
  flutter_gen_runner: ^5.1.0+1 # flutter_gen support

  #JSON support
  json_serializable: ^6.6.0

  #utils
  flutter_lints: ^2.0.0

  #reactive form generator
  reactive_forms_generator: ^0.23.4

flutter:

  uses-material-design: true

  # enable the generate flag
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/background/
    - fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Gotham
      fonts:
        - asset: fonts/GothamBook.ttf
          weight: 400
        - asset: fonts/GothamBold.ttf
          weight: 700
        - asset: fonts/GothamMedium.ttf
          weight: 500

flutter_gen:
  output: lib/gen/  # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true

    assets:
      enabled: true
      outputs:
        class_name: AppAssets
        package_parameter_enabled: false
        # Assets.images.chip (default style)
        style: dot-delimiter

#flutter_intl:
#  enabled: true
